### ISSUE TITLE
PhoneNumber constraints in validation.yml

### ISSUE THREAD

**Issue by ugurerkan** [misd-service-development/phone-number-bundle#104]
Hello,

I was trying to use phone number validation in a bundle validation.yml file, but got an exception says default options is not configured.  

There is any way to validate entity with yaml file or I'm doing something wrong?

**Exception Message**
```
No default option is configured for constraint Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber
```

**validation.yml**
```yml
UserBundle\Entity\User:
    constraints:
        - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber: PhoneNumber
    properties:
        name:
            - NotBlank: ~
        surname:
            - NotBlank: ~
        mobile:
            - PhoneNumber: ~
```

**Comment by xabbuh** [comment]
Why did you add the constraint to the class level and did not attach it to the property holding the actual phone number?

This would then look something like this:

```yaml
UserBundle\Entity\User:
    properties:
        name:
            - NotBlank: ~
        surname:
            - NotBlank: ~
        mobile:
            - Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber: ~
```
