### ISSUE TITLE
Unable to transform value for property path phone

### ISSUE THREAD

**Issue by kojiDev** [misd-service-development/phone-number-bundle#121]
It's basically the same issue that [this](https://github.com/misd-service-development/phone-number-bundle/issues/103) guy faced, but he doesn't seem to interesting it anymore.

I did everything by readme, but Doctrine still complains about type incompatibility:

> php bin/console doctrine:fixtures:load
> purging database
> loading AppBundle\DataFixtures\ORM\LoadFixtures                                   
> [Doctrine\DBAL\Types\ConversionException] Expected \libphonenumber\PhoneNumber, got string

User class
```
namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Misd\PhoneNumberBundle\Validator\Constraints\PhoneNumber as AssertPhoneNumber;

@ORM\Entity
class User
{
    /**
     * @ORM\Column(type="phone_number", nullable=true)
     * @AssertPhoneNumber
     * @Serializer\Type("libphonenumber\PhoneNumber")
     *
     * @var string
     */
    private $phone;

    public function setPhone(?string $phone = null)
    {
        $this->phone = $phone;
    }

    public function getPhone(): string
    {
        return $this->phone;
    }
}
```
config.yml
```
doctrine:
    dbal:
        ...
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
```
fixture file:
```
AppBundle\Entity\User:
    user_john:
        firstname: John
        lastname: Johnson
        email: some@email.com
        phone: +79990000001
````

Where should magic of transformation go?
Should I create EventListener that will be transform string -> PhoneNumber after fetching data from DB and vice versa?
