### ISSUE TITLE
Unable to find template "MisdPhoneNumberBundle:Form:tel_bootstrap.html.twig" for Symfony 3.4 project

### ISSUE THREAD

**Issue by c0ntax** [misd-service-development/phone-number-bundle#158]
I've been trying to get this Bundle to work in a Symfony 3.4 project (built using Flex) and I get the following error when trying to use the telephone type in a form:

```Unable to find template "MisdPhoneNumberBundle:Form:tel_bootstrap.html.twig"```

As far as I can tell, the compiler pass for the Twig is working correctly, but Twig can't seem to find the template. I had a play around with things and found that if I changed the template names to:

```php
    private $telLayout = '@MisdPhoneNumberBundle/Form/tel.html.twig';
    private $telBootstrapLayout = '@MisdPhoneNumberBundle/Form/tel_bootstrap.html.twig';
```

in ```DependencyInjection/Compiler/FormTwigTemplateCompilerPass.php``` and then added the following to my twig config:

```yaml
twig:
    paths:
        '%kernel.project_dir%/vendor/misd/phone-number-bundle/Resources/views': MisdPhoneNumberBundle
```

It then all works... Which doesn't seem to me to be the 'right' thing to do. Am I using the Bundle incorrectly, or is this a bug?

I'm going to fork and 'fix' this issue, but I don't know if this is the right way to fix it.
