### ISSUE TITLE
FOSUserBunder with my own user_provider get ErrorException: Catchable Fatal Error: Argument 1 passed to libphonenumber\PhoneNumberUtil::format() 

### ISSUE THREAD

**Issue by AndreyEQ** [misd-service-development/phone-number-bundle#18]
Hello

My name is Andrey. I use FOSUserBundle for my project. 
I need users to login via phone_number ONLY.
So I use you bundle. Its great!
add provider in security.yml

``` yaml
providers:
        fos_userbundle:
            #id: fos_user.user_provider.username
            id: equils_user.user_provider.phone
```

add in services.yml

``` yaml
    equils_user.user_provider.phone:
        class: Equils\UserBundle\Security\PhoneUserProvider
        arguments: [@equils_user.user_manager.default]

    equils_user.user_manager.default:
        class: Equils\UserBundle\Doctrine\UserManager
        arguments:
            - @security.encoder_factory
            - @fos_user.util.username_canonicalizer
            - @fos_user.util.email_canonicalizer
            - @fos_user.entity_manager
            - %fos_user.model.user.class%
```

add classes 

``` php
/**
 */
namespace Equils\UserBundle\Security;
use FOS\UserBundle\Security\UserProvider as BaseProvider;
use FOS\UserBundle\Model\UserManagerInterface;

class PhoneUserProvider extends BaseProvider
{
    /**
     * @var UserManagerInterface
     */
    protected $userManager;

    /**
     * Constructor.
     *
     * @param UserManagerInterface $userManager
     */
    public function __construct(UserManagerInterface $userManager)
    {
        $this->userManager = $userManager;
    }

    /**
     * Finds a user by phone number.
     *
     * @param string $phone
     *
     * @return UserInterface|null
     */
    protected function findUser($phone)
    {
        return $this->userManager->findUserByPhoneNumber($phone);
    }

}
```

``` php
/**
 */
namespace Equils\UserBundle\Doctrine;

use Doctrine\Common\Persistence\ObjectManager;
use FOS\UserBundle\Util\CanonicalizerInterface;
use Symfony\Component\Security\Core\Encoder\EncoderFactoryInterface;
use FOS\UserBundle\Doctrine\UserManager as BaseManager;

class UserManager extends BaseManager
{
    public function __construct(EncoderFactoryInterface $encoderFactory, CanonicalizerInterface $usernameCanonicalizer, CanonicalizerInterface $emailCanonicalizer, ObjectManager $om, $class)
    {
        parent::__construct($encoderFactory, $usernameCanonicalizer, $emailCanonicalizer, $om, $class);
    }

    /**
     * Finds a user by phone number
     *
     * @param string $phone
     *
     * @return UserInterface
     */
    public function findUserByPhoneNumber($phone)
    {
        return $this->findUserBy(array('phone_number' => $phone));
    }
}
```

and so on... but 
when I try to log in I get error:

![22 10](https://cloud.githubusercontent.com/assets/9293590/4723539/89ee8228-5948-11e4-8ecb-156af36bc38a.png)

 I found place in code where I guess error happen and fix that...

``` php
/**
     * {@inheritdoc}
     */
    public function convertToDatabaseValue($value, AbstractPlatform $platform)
    {
        if (null === $value) {
            return null;
        }

        $phoneNumber = PhoneNumberUtil::getInstance()->parse($value, 'RU');
        $util = PhoneNumberUtil::getInstance();

        return $util->format($phoneNumber, PhoneNumberFormat::E164);
    }
```

Please tell me, what do you think about this fix. Is it valid ?
