### ISSUE TITLE
get error  Could not convert database value "" to Doctrine Type phone_number 

### ISSUE THREAD

**Issue by xorgxx** [misd-service-development/phone-number-bundle#58]
Hi thank for this bundle, how is going to be userfull for me to!
i have just install lake description, and i get : ``` Could not convert database value "" to Doctrine Type phone_number ```

here my config : 
```
doctrine:
    dbal:
        types:
            phone_number: Misd\PhoneNumberBundle\Doctrine\DBAL\Types\PhoneNumberType
```
in builder form : 
```
    use libphonenumber\PhoneNumberFormat;
...........................

                    ->add ( 'phoneNumber', 'tel', array(
                        'default_region' => 'GB',
                        'format' => PhoneNumberFormat::NATIONAL)
                    )
```
twig : 
```
...........
    {{ form(edit_form) }}
...........
```
entity : 
```
       /**
         * @ORM\Column(type="phone_number")
         */
        private $phoneNumber;
```

can you help me ?

thank
